### ISSUE TITLE
обученная модель

### ISSUE THREAD

**Issue by nikolaev-dm** [chipslays/cracker#1]
Планируется ли выложить обученную модель?

**Comment by chipslays** [comment]
Привет! К сожалению, в данный момент не планируется.

**Comment by nikolaev-dm** [comment]
@chipslays Спасибо за ответ, очень жаль. Ещё тогда такой вопрос: в readme указан [репозиторий](https://github.com/guiem/train-tesseract.git), на основе которого обучается модель. Я немного некомпетентен в ML.. У меня есть тестовые данные (капча и правильный ответ), но без документации не могу разобраться как начать обучать. Можете обновить readme и показать пример того, как можно это сделать?

**Comment by chipslays** [comment]
> @chipslays Спасибо за ответ, очень жаль. Ещё тогда такой вопрос: в readme указан [репозиторий](https://github.com/guiem/train-tesseract.git), на основе которого обучается модель. Я немного некомпетентен в ML.. У меня есть тестовые данные (капча и правильный ответ), но без документации не могу разобраться как начать обучать. Можете обновить readme и показать пример того, как можно это сделать?

Попробуй посмотреть [эту](https://guiem.medium.com/how-to-train-tesseract-4-ebe5881ff3b7) статью, должно помочь 🙂
